### PR TITLE
Update nginx.conf

### PR DESCRIPTION
**Pull request by protocolpaladin**

### CODE REVIEW

**Comment by protocolpaladin** [comment]
add compatibility behind reverse proxy example: traefik https

**Comment by protocolpaladin** [comment]
and if not impact http if not behind reverse proxy

**Comment by dbarzin** [comment]
Thanks !

**Comment by protocolpaladin** [comment]
please delete

space tab it's and error copy past

sub_filter_once off;
	sub_filter_types text/html;
	sub_filter "http://mercator." "https://mercator.";

sub_filter_once off;
sub_filter_types text/html;
sub_filter "http://mercator." "https://mercator.";

:)

**Pull request merged**
